services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "5050:5000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ../BookStore-data_collection/data:/app/data
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - FLASK_APP=${FLASK_APP}

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/postgres-data
    ports:
      - "5432:5432"
