FROM python:3.12-alpine3.20

WORKDIR /app

RUN pip install --upgrade pip

RUN apk add --no-cache \ 
    postgresql15 \
    build-base

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./

COPY scripts/start-prod.sh start.sh

# Ensure the script is executable
RUN chmod +x start.sh

ENTRYPOINT [ "/app/start.sh" ]

# Expose the port your application will run on
EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:create_app()"]
