FROM python:3.12-alpine3.20

WORKDIR /app

RUN pip install --upgrade pip

RUN apk add --no-cache \ 
    postgresql15 \
    build-base \
    git

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "/app/docker/scripts/start-test.sh" ]

CMD ["./watcher", "pytest tests -vvv"]
