"""empty message

Revision ID: 05298847be03
Revises: 
Create Date: 2024-11-23 05:40:17.788877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05298847be03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('isbn_10', sa.String(), nullable=True),
    sa.Column('isbn_13', sa.String(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('previous_price', sa.Float(), nullable=True),
    sa.Column('physical_format', sa.String(), nullable=True),
    sa.Column('number_of_pages', sa.Integer(), nullable=True),
    sa.Column('editorial', sa.String(), nullable=True),
    sa.Column('alejandria_isbn', sa.String(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('physical_dimensions', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('publish_place', sa.String(), nullable=True),
    sa.Column('edition_name', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_alejandria_isbn'), ['alejandria_isbn'], unique=True)
        batch_op.create_index(batch_op.f('ix_book_isbn_10'), ['isbn_10'], unique=True)
        batch_op.create_index(batch_op.f('ix_book_isbn_13'), ['isbn_13'], unique=True)

    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_genres',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.create_table('book_languages',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'language_id')
    )
    op.create_table('book_series',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'series_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_series')
    op.drop_table('book_languages')
    op.drop_table('book_genres')
    op.drop_table('book_authors')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_isbn_13'))
        batch_op.drop_index(batch_op.f('ix_book_isbn_10'))
        batch_op.drop_index(batch_op.f('ix_book_alejandria_isbn'))

    op.drop_table('book')
    op.drop_table('series')
    op.drop_table('publisher')
    op.drop_table('language')
    op.drop_table('genre')
    op.drop_table('author')
    # ### end Alembic commands ###
