"""empty message

Revision ID: 3865b0540a74
Revises: 5ff28fff0880
Create Date: 2024-12-15 11:03:54.487417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3865b0540a74'
down_revision = '5ff28fff0880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index('ix_book_bar_code_alejandria')
        batch_op.drop_index('ix_book_code_alejandria')
        batch_op.drop_index('ix_book_isbn_alejandria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index('ix_book_isbn_alejandria', ['isbn_alejandria'], unique=False)
        batch_op.create_index('ix_book_code_alejandria', ['code_alejandria'], unique=False)
        batch_op.create_index('ix_book_bar_code_alejandria', ['bar_code_alejandria'], unique=False)

    # ### end Alembic commands ###
