"""empty message

Revision ID: 3a2af2853839
Revises: ed64ddf1f5e1
Create Date: 2025-01-01 03:33:59.725060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2af2853839'
down_revision = 'ed64ddf1f5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
