"""empty message

Revision ID: 60131ebd6b74
Revises: a854f8bb4829
Create Date: 2025-04-03 15:53:04.221975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60131ebd6b74'
down_revision = 'a854f8bb4829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
