"""empty message

Revision ID: 72de8dcd87d0
Revises: 9c49f9ddd43d
Create Date: 2024-12-30 01:26:48.841177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72de8dcd87d0'
down_revision = '9c49f9ddd43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('id_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('id_type')
        batch_op.drop_column('id_number')
        batch_op.drop_column('status')
        batch_op.drop_column('session_token')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('tax')

    op.drop_table('promotions')
    # ### end Alembic commands ###
