"""empty message

Revision ID: 8c0a180727ce
Revises: 3a2af2853839
Create Date: 2025-01-01 03:37:10.878413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0a180727ce'
down_revision = '3a2af2853839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=1, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Numeric(precision=1, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
