"""empty message

Revision ID: d1581974fcd1
Revises: 79d0e305b245
Create Date: 2025-03-26 21:43:28.463724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1581974fcd1'
down_revision = '79d0e305b245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
