"""empty message

Revision ID: ed64ddf1f5e1
Revises: 84a2a3bc033f
Create Date: 2024-12-31 00:57:08.249794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed64ddf1f5e1'
down_revision = '84a2a3bc033f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('conditions', sa.JSON(), nullable=True))
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.INTEGER(), nullable=False))
        batch_op.drop_column('conditions')
        batch_op.drop_column('discount_value')
        batch_op.drop_column('discount_type')

    # ### end Alembic commands ###
