services:

  flask-app:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile-prod
    ports:
      - "5050:5000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ${DATA_PATH}:/data
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - FLASK_APP=${FLASK_APP}
      - FLASK_CONFIG=production

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
