services:

  flask-app:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/Dockerfile-test
    depends_on:
      - postgres
    volumes:
      - ../../:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - FLASK_APP=${FLASK_APP}
      - FLASK_CONFIG=testing

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
